### ISSUE TITLE
Allow loading sphinx declarations if avaialble

### ISSUE THREAD

**Issue by harlowja** [twolfson/restructuredtext-lint#11]
When trying to validate sphinx files docutils (and by association restructredtext-lint) pukes a bunch of errors that are false positives that are actually ok. I've had to work around this in https://github.com/stackforge/doc8 (which is used in a few openstack projects now btw) at https://github.com/stackforge/doc8/blob/master/doc8/checks.py#L79 ; is there any better option that can be used to avoid those types of non-errors that this helper program can make possible. Possibly loading the sphinx extensions so they aren't warnings/errors? Thoughts?

**Comment by harlowja** [comment]
So I see the following which has something maybe we can do?

https://github.com/myint/rstcheck/blob/master/rstcheck.py#L323

https://pypi.python.org/pypi/rstcheck (pretty similar to this code-base in some ways)....

**Comment by twolfson** [comment]
Right, they are leveraging directives and roles as mentioned in the previous comment. Are you still interested in opening a PR?

**Comment by harlowja** [comment]
Let me see if I can; I'd like to so that I can get rid of https://github.com/stackforge/doc8/blob/master/doc8/checks.py#L99 (and such crap... there).

**Comment by twolfson** [comment]
Closing as wontfix for the same reasons as given in #14. We have added documentation for adding new directives/roles via `docutils` in `0.11.3`.

https://github.com/twolfson/restructuredtext-lint/pull/14#issuecomment-91933907
