### ISSUE TITLE
Create a http://readthedocs.org/ site

### ISSUE THREAD

**Issue by harlowja** [twolfson/restructuredtext-lint#15]
Instead of having the docs here which are starting to get overwhelming/messy (IMHO) how about having a site that's connected to http://readthedocs.org/ and host the docs there instead (github afaik can trigger http://readthedocs.org/ jobs on commits so that it can be auto-updated). Thoughts?

**Comment by twolfson** [comment]
Unfortunately, I disagree. At the moment, the docs are terse and each section is well contained. If we broke it up now, then it would be a paragraph on a webpage which is impractical to read/use. Going to say no for now.
