### ISSUE TITLE
Use absolute imports for python 3 compatibility

### ISSUE THREAD

**Issue by fizyk** [twolfson/restructuredtext-lint#20]
We're using restructuredtext-lint to make lint our README and CHANGELOG, to limit the cases where pypi page doesn't get rendered, and it failed today on all python 3 builds:

https://travis-ci.org/ClearcodeHQ/mirakuru/jobs/66110072

This is due to python 3 requiring absolute imports, or the relative one starting with a .

**Comment by twolfson** [comment]
This has been patched/released in `0.12.2` via @fizyk in #20. Thanks again for the report/fix =)
