### ISSUE TITLE
coala

### ISSUE THREAD

**Issue by sils1297** [twolfson/restructuredtext-lint#22]
Hey,

we're working on a tool that makes it very easy to create "code checking routines" and provide you with the whole user interaction (from JSON output via interactive CLI UI to an actual GUI and we're working on things like direct GitHub integration and stuff like that) and collection routines for free.

We'd be interested in porting your routines over to our project so you get a better user interaction for them (and we get a bit more analysis). Would you be interested in porting your analysis over to coala? I'd be glad to assist you.

This would of course solve https://github.com/twolfson/restructuredtext-lint/issues/8 and add a lot of usability features. It would also allow you to do things like attaching a patch to a result so coala can auto-fix it for the user if he wishes so.

More info also on coala-analyzer.org , I'm also happy to answer any questions you might have right here.

**Comment by twolfson** [comment]
Can you elaborate on why we should port and `coala` can't use this module as is?

**Comment by sils1297** [comment]
@twolfson sure! Using coala directly is usually better for the user than just a simple wrapper though a *good* wrapper can emulate almost the same. In the end the advantages depend on how your current architecture is, from what I can see so far, the advantages would be:

1. We maintain the stuff for or with you. Either case, less work for you, possibly better quality. Ideally you'd stay the maintainer of that part within coala.
2. We've got a more flexible result object. By porting to coala you get a few goodies: your checker routines (or whatever you call them) can now for example associate multiple related source code ranges with a result (e.g. a code clone, not that relevant for rst though but still one might have relations between things) or it could append a patch to the result allowing coala to offer the user to automatically fix the issue. Especially the last thing makes the life of the users very easy and usually makes the difference for actually fixing an issue or not.
3. Less stuff to maintain in general. Of course less documentation to maintain also.

All that needs to be ported as far as I see is https://github.com/twolfson/restructuredtext-lint/blob/master/restructuredtext_lint/lint.py and of course the tests. Since you're already python it's a quick thing to do.

It comes down to less work for you and better overall maintainability and flexibility at a rather small cost. Since we're interested in adoption for our tool and making it better for users we'd assist you heavily when porting.

Of course if you do not wish so there's no need. We can also do a wrapper with the named disadvantages.

**Comment by twolfson** [comment]
While I understand what you are saying, I don't understand what would change about the data returned from our package. Can you provide an example?

**Comment by sils1297** [comment]
how about discussing this interactively on https://gitter.im/coala-analyzer/coala ? Are you asking about the 2. point?

**Comment by sils1297** [comment]
maybe the simplest thing is if you look at one of our algorithms, coala is modular so you just write a class with a run routine (we'll probably refactor that into a nice decorator soon) like this: https://github.com/coala-analyzer/coala/blob/master/bears/spacing/SpaceConsistencyBear.py#L67 , the routine just yields on any issues it finds.

**Comment by twolfson** [comment]
Yes, I was talking about (2). Sorry but I'm not free to use something like gitter at the moment.

I am open to changing our API to make it more friendly (e.g. adding an iterator interface, adding more metadata) but as far as moving it to another repository, I'm not convinced in there being any benefit.

From my perspective, I prefer to follow the "One thing well" methodology meaning that this repo specializes in linting RST documents. It allows us to have a verbose and targeted test suite without being overwhelmed by other unrelated tests. It also allows this package to be reused by not only `coala` but other packages like `doc8`.

https://github.com/openstack/doc8/blob/0.6.0/requirements.txt#L8

I'm closing this issue as "wontfix" for now. If you would like an iterator interface or any other metadata we are not returning, please open separate issues.

**Comment by sils1297** [comment]
The "do one thing well" ideology is close to us as well: think about it, with coala we want you to do the logic well and us the user interaction. Right now you're doing both. And so is everyone else which is a big redundancy across projects. coala helps you to narrow your scope. BTW. coala-format should allow you to emulate your old API using a format string, that shouldn't be the responsibility of you. Do one thing.

There is no need to put cpplint into our repository, you can use coala as a dependency and splitting out our analysis into meaningful groups by means of repositories is on our plate anyway. (We're freetimers so it needs something concrete for it to actually happen). With that happening coala would get rid of its number of dependencies.

I fully understand if you don't wish to do so but speaking about our intentions is better than just writing a wrapper IMO and may save a lot work. Changing your framework is probably more work than just making it a bear for coala, only a few lines change and a lot of code removed.

**Comment by twolfson** [comment]
I believe we have varying opinions of how to interpret "One thing well" and how to architect our projects.

In my opinion, "One thing well" is with respect to the size/scope of the project. I do consider both the CLI and API to be different entities. However, in this project they are both quite small and can coexist in the same repo since that's easier to maintain. If my CLI becomes too large or too complex, then I would break it out as its own repo which would depend on `restructuredtext-lint`.

With respect to using `coala` as a framework, I would consider loading all of `coala` to only lint for RST to be overkill. It's like building a car when all you needed was a tire. I don't want to force people to download excess content that they aren't going to be using.

**Comment by sils1297** [comment]
OK, thanks for sharing your opinion!

**Comment by sils1297** [comment]
In case you're interested, I just wrote the wrapper for coala ([sample output](http://pastebin.com/Xfq6sHLR)). When this gets merged, you can use your reST lint right in several editors (Atom, Sublime, Gedit) via coala or let it automatically check your PRs via our (prototype) service gitmate.com .

Thanks for providing a nice API. :)

**Comment by twolfson** [comment]
Neat, glad to hear everything worked out =)
