### ISSUE TITLE
opt-in automated link checking

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [twolfson/restructuredtext-lint#30]
hi, we use this tool to check out changelog,
with great success, it is now internally consistent

however it still happens regular, that we find typos or mistakes in links and would like to check those in detail

would something like this be in scope for this project?

**Comment by twolfson** [comment]
I don't think it's in scope for this project; I feel like it's too much maintenance for too low usage. A quick and dirty implementation for you should be something like running `rst2html` (from `docutils`) and something that checks links on HTML documents (don't have anything in mind but sure these exist).

Annoying edge cases will include: relative links, script links
