### ISSUE TITLE
Validating docstrings in Python files as RST

### ISSUE THREAD

**Issue by peterjc** [twolfson/restructuredtext-lint#34]
As I understand it, ``rst-lint *.rst`` works great on plain text files using reStructuredText.

I would like to be able to do ``rst-lint *.py`` and have it pull out the Python docstrings, and check if they are valid reStructuredText.

Ideally any errors would retain the original line number from the Python file. That can probably be done via an offset if processing each docstring alone.

**Comment by twolfson** [comment]
I would like to keep this module as 1 thing well and defer to using a `bash`/Python glue script for that behavior. I don't know any programs off the top of my head to pull out docstrings but I'm sure they exist due to automated documentation creation. An example script would look like:

```bash
for file in *.py; do
  extract-docstrings "$file" | rst-lint -
done
```

**Comment by peterjc** [comment]
OK, if we discover such a extract-docstrings tool, then it would be good to add an example like this to the documentation for your tool.

**Comment by twolfson** [comment]
Yea, I would be open to adding that in the "Examples" section :+1:

**Comment by peterjc** [comment]
In pull request https://github.com/PyCQA/pydocstyle/issues/254 I wrote a proof-of-principle extending ``pydocstyle`` to validate Python docstrings as RST using the approach from Todd's ``restructuredtext-lint`` code.

However, the ``pydocstyle`` team recommend this functionality instead be written as a new plugin for ``flake8`` - see https://gitlab.com/pycqa/flake8/issues/337

**Comment by twolfson** [comment]
Both make sense (i.e. `flake8` plugin, CLI tool) but it seems that both `pydocstyle` and myself concur that it should be another library that finds/extracts the docstrings for comparison

**Comment by peterjc** [comment]
I've started working on this as a flake8 plugin under the name ``flake8-rst-docstrings``,

https://github.com/peterjc/flake8-rst-docstrings

**Comment by peterjc** [comment]
I've made the first release of the new plugin ``flake8-rst-docstrings`` on PyPI, which uses ``restructuredtext-lint`` internally:

https://pypi.python.org/pypi/flake8-rst-docstrings

(I'll stop commenting on this issue now - thanks)
