### ISSUE TITLE
Detect CR/LF Issue

### ISSUE THREAD

**Issue by shane-mason** [twolfson/restructuredtext-lint#36]
I was having a problem on Pypi with my README.rst where it was being truncated after the first line. A few Google searches later and I found this linter - which I appreciate since pypi is very picky and silent. Unfortunately, rst-lint returned a clean bill of health. I checked the file settings and it appears that PyCharm set the file to CR/LF line endings - which shouldn't choke Pypi but apparently did. Here is the project:

http://pypi.python.org/pypi/essentialdb/

I changed the file to just LF and Pypi was happy again. You can look back at versions 0.3.0 - 0.3.19 to see the issue. Might want to add that as a warning at least?

**Comment by twolfson** [comment]
Thanks for writing in! Unfortunately, I'm going to mark this as a `wontfix`. After some playing around, it looks like `docutils` (the canonical package for reStructuredText) support both `LF` and `CRLF` variations =/ (i.e. `rst2html.py` works on `LF` and `CRLF` files)

I don't think it's best to exclusively target for the PyPI case as there could be other scenarios where people want to use `CRLF` (e.g. a team of Windows developers working on an internal project)
