### ISSUE TITLE
Supply directory names at command line to search

### ISSUE THREAD

**Issue by peterjc** [twolfson/restructuredtext-lint#38]
Related Python linting tools like ``pep8``, ``flake8`` and ``pydocstyle`` will accept a mixture of filenames and directory names (e.g. ``.``, ``Tests`` or ``Tests/``). When a directory is given, they appear to recurse under it and lint any matching files (here presumably using ``*.py``).

I would like to be able to run commands like ``rst-lint *.rst Scripts/ Tests/`` or just ``rsl-lint .`` and have it recurse under the given directories to find ``*.rst`` files. This pattern might be set by a new optional argument.

**Comment by twolfson** [comment]
This sounds like a reasonable feature. Marking it as "help wanted"

**Comment by twolfson** [comment]
Fwiw, `rst-lint *.rst` isn't great as it expands on `bash` yet not on Windows so definitely we wouldn't want to expand globs in this feature. Otherwise, we would have trouble knowing whether to look for a literal `*` or to expand it

**Comment by peterjc** [comment]
I presume ``flake8`` etc have solved the Windows wildcard expansion issue, so we can likely copy their tested solution for the wildcards.

**Comment by twolfson** [comment]
`flake8` doesn't support wildcard expansion. Here's some example commands to verify that:

```
$ flake8 *.py --verbose
flake8.plugins.manager    MainProcess    102 INFO     Loading entry-points for "flake8.extension".
...
flake8.checker            MainProcess    129 INFO     Making checkers
flake8.checker            MainProcess    132 INFO     Checking 2 files
...
$ flake8 '*.py' --verbose
flake8.plugins.manager    MainProcess     97 INFO     Loading entry-points for "flake8.extension".
...
flake8.checker            MainProcess    121 INFO     Making checkers
flake8.checker            MainProcess    123 INFO     Checking 0 files
...
```

**Comment by twolfson** [comment]
Support for this has been added in `1.2.0` via @dhruvsomani in #48
