### ISSUE TITLE
Inquiry on Python virtualenv support

### ISSUE THREAD

**Issue by lextm** [twolfson/restructuredtext-lint#40]
Thanks for creating this wonderful tool.

I am not familiar with Python, but maintaining the reStructuredText/Sphinx extension for Visual Studio Code.

To support Python virtualenv setup, the extension can call sphinx document generator via `python -msphinx` instead of `sphinx-build`,

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/src/features/rstDocumentContent.ts#L36

However, when trying to integrate with `restructuredtext-lint`, how can I call it via `python`? Do you support something like `python -mrestructuredlint`?

**Comment by twolfson** [comment]
The short answer is yes, here's the command that will work:

```bash
python -m restructuredtext_lint.cli
```

The long answer is yes, `python -m {{import-path}}` operates by attempting to run `import {{import-path}}` and executing it (e.g. `python -m foo.bar` loads the file `bar` in the `foo` module). We have a hook that auto-runs the `cli` logic when its loaded directly

https://docs.python.org/2/using/cmdline.html#cmdoption-m

To find our CLI integration, we can look at our `setup.py` which has a similar setup for `console_scripts`:

https://github.com/twolfson/restructuredtext-lint/blob/1.1.1/setup.py#L28

```
'restructuredtext-lint = restructuredtext_lint.cli:main',
```

After tweaking the syntax, we get:

```bash
python -m restructuredtext_lint.cli
```

**Comment by lextm** [comment]
Thanks. Works like a charm.
