### ISSUE TITLE
'caption' not recognized in code-block directive

### ISSUE THREAD

**Issue by jpsenior** [twolfson/restructuredtext-lint#42]
When using a code-block as such:

```
.. code-block:: text
    :caption: This is some text
    
     This is example text
```

rst-lint fails with an error: 'Error in "code-block" directive: unknown option "caption"'

Omitting the caption has no error.

**Comment by twolfson** [comment]
It sounds like `caption` isn't a built-in directive to reStructuredText and needs to be registered. Please see our "Extension" documentation for the necessary info/methods:

https://github.com/twolfson/restructuredtext-lint/tree/1.1.1#extension
