### ISSUE TITLE
pre-commit hook

### ISSUE THREAD

**Issue by rpdelaney** [twolfson/restructuredtext-lint#50]
Hey again Todd :) Found this repo via Google, I swear.

I've been using [pre-commit](https://pre-commit.com/) lately and it's pretty cool. I wonder if you think it would be useful to create a hook module for `rstlint` since I have had this annoying problem several times as well. I have a lot on my plate but if you're interested I could put something together when I get a chance. Let me know what you think.

**Comment by rpdelaney** [comment]
Yeah, the idea is you add a line to `.pre-commit-config.yaml` in your git repo and pre-commit loads the hooks like a module. It's pretty much just a package manager for pre-commit hooks. Kind of a neat idea. There are some examples [here](https://github.com/pre-commit/pre-commit-hooks). You pick and choose the ones you want. 

Come to think of it, I'm not sure I actually need anything from you to do this. The modules for the hooks are their own separate repos. I'm still learning about pre-commit though and how it works. I'll try to spin something up and let you know if I get it working. I suppose you can probably close this issue.

**Comment by twolfson** [comment]
Heh, okie doke. Yep, going to eagerly close this issue

Feel free to re-open if we find out otherwise

**Comment by ssbarnea** [comment]
Refusal to add pre-commit hook seems like a good enough reason for me to avoid using this linter, even if there was a desired to add linting for that. That hook config can be found on almost all python linters and requires no maintenance at all. In fact it acts as metadata.

**Comment by rpdelaney** [comment]
I think we beat the topic into the ground when we discussed it last year in this issue: https://github.com/twolfson/restructuredtext-lint/pull/51

**Comment by ssbarnea** [comment]
Not sure how I missed that. Meanwhile [doc8](https://github.com/PyCQA/doc8) supports it and also integrates with https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext
