### ISSUE TITLE
Transition to Python 3

### ISSUE THREAD

**Issue by khashf** [twolfson/restructuredtext-lint#53]
I'm porting my project to `python3` as `python2` will be [EOL in 2020](https://pythonclock.org/). I'm following [this recommended procedure](https://docs.python.org/3/howto/pyporting.html#check-which-dependencies-block-your-transition) which includes using `caniusepython3` to figures out which of them are holding me up from porting to Python 3.

`caniusepython3` warns me about `restructuredtext-lint` needing to transition to python3.

```
$ caniusepython3 -r requirements.txt 
Finding and checking dependencies ...
[WARNING] problem fetching pkg-resources, assuming ported (404)

You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  restructuredtext-lint
```

I'm using `restructuredtext-lint` version `1.3.0`
```
$ cat requirements.txt | grep restructuredtext-lint
restructuredtext-lint==1.3.0 
```

Do you have a plan for porting to python3?

What can I help?

Thanks! :)

**Comment by twolfson** [comment]
I'm unsure what is causing that issue. The website seems to be loading indefinitely for our results and occasionally giving a 500 =/ We do test against Python 3 so you're good to use it freely

https://caniusepython3.com/project/restructuredtext-lint

https://github.com/twolfson/restructuredtext-lint/blob/1.3.0/.travis.yml#L4-L8

https://travis-ci.org/twolfson/restructuredtext-lint/builds/510426058
