### ISSUE TITLE
Lint failing with html

### ISSUE THREAD

**Issue by vinaysb** [twolfson/restructuredtext-lint#54]
When I try to run rst-lint on my README file I get the warning, 
```
WARNING README.md:3 Definition list ends without a blank line; unexpected unindent.
WARNING README.md:7 Definition list ends without a blank line; unexpected unindent.
```
This is how my README looks like, 
```
<p align="center">
  <img src="img.jpg" height="800">
</p>

<h1 align="center">
  IMAGE
</h1>
```

**Comment by twolfson** [comment]
HTML isn't valid reStructuredText. It's unclear whether you want this to be a code block or README content so here are your possible options:

## reStructuredText version of code
```rst
.. image:: img.jpg
  :height: 800

IMAGE
-----
```

http://docutils.sourceforge.net/docs/ref/rst/directives.html#images

## reStructuredText with raw HTML
```rst
.. raw:: html
    <p align="center">
      <img src="img.jpg" height="800">
    </p>

    <h1 align="center">
      IMAGE
    </h1>
```

http://docutils.sourceforge.net/docs/ref/rst/directives.html#raw-data-pass-through

## reStructuredText with HTML in code block
```rst
.. code:: html
    <p align="center">
      <img src="img.jpg" height="800">
    </p>

    <h1 align="center">
      IMAGE
    </h1>
```

http://docutils.sourceforge.net/docs/ref/rst/directives.html#code
