### ISSUE TITLE
CLI silently ignores non-existent files

### ISSUE THREAD

**Issue by jwilk** [twolfson/restructuredtext-lint#58]
When I misspelled the name of the file to check, rst-lint gave me no hint that anything is wrong. ☹

```console
$ rst-lint --version
1.3.2

$ rst-lint RAEDME.rst && echo OK
OK
```
This is regression introduced in 1221b234f614672be9b2bf2569fefeb7a5756d40 ("Updated recursion method and added better tests" by @dhruvsomani).
Before that, you would get:

```console
$ rst-lint RAEDME.rst
Traceback (most recent call last):
  File "/home/jwilk/.local/bin/rst-lint", line 8, in <module>
    sys.exit(main())
  File ".../restructuredtext_lint/cli.py", line 103, in main
    _main(**args.__dict__)
  File ".../restructuredtext_lint/cli.py", line 47, in _main
    for file in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'RAEDME.rst'
```

**Comment by twolfson** [comment]
Oh wow, that's quite the regression O_O The logic really should be `if file, elif directory, else raise`. Do you mind opening a PR to fix that (and possibly a test if easily done)?

**Comment by jwilk** [comment]
I don't have time to tackle this. Sorry!

**Comment by twolfson** [comment]
Ah, darn =/ Going to see if I can pick this up now, doesn't look **too** bad

**Comment by twolfson** [comment]
After some wrangling of virtualenv/virtualenvwrapper, finally actually reproduced the issue =)

**Comment by twolfson** [comment]
The patch is live in `1.4.0`. Thanks for the bug report =D
